version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DATABASE_URL=sqlite:./data/data.db
      - FRONTEND_URL=http://localhost:5173
      - RUST_LOG=info
      - JWT_SECRET=${JWT_SECRET:-your_secret_key_for_jwt_tokens_change_in_production}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Uncomment this section if you want to add a frontend service
  # frontend:
  #   image: nginx:alpine
  #   ports:
  #     - "5173:80"
  #   volumes:
  #     - ./frontend/dist:/usr/share/nginx/html
  #   depends_on:
  #     - api
  #   restart: unless-stopped
